import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";

export const RobotModel = (props) => {
  const group = useRef();
  const { nodes, materials } = useGLTF("/robot.glb");
  //   const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} dispose={null}>
      <group name="Scene" position={[0, -2.2, 0]} ref={props.objectRef}>
        <group name="Armature" rotation={[Math.PI / 2, 0, -0.95]} scale={0.02}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="character_tpose"
            geometry={nodes.character_tpose.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose.skeleton}
          />
          <skinnedMesh
            name="character_tpose001"
            geometry={nodes.character_tpose001.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose001.skeleton}
          />
          <skinnedMesh
            name="character_tpose002"
            geometry={nodes.character_tpose002.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose002.skeleton}
          />
          <skinnedMesh
            name="character_tpose003"
            geometry={nodes.character_tpose003.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose003.skeleton}
          />
          <skinnedMesh
            name="character_tpose004"
            geometry={nodes.character_tpose004.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose004.skeleton}
          />
          <skinnedMesh
            name="character_tpose005"
            geometry={nodes.character_tpose005.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose005.skeleton}
          />
          <skinnedMesh
            name="character_tpose006"
            geometry={nodes.character_tpose006.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose006.skeleton}
          />
          <skinnedMesh
            name="character_tpose007"
            geometry={nodes.character_tpose007.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose007.skeleton}
          />
          <skinnedMesh
            name="character_tpose008"
            geometry={nodes.character_tpose008.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose008.skeleton}
          />
          <skinnedMesh
            name="character_tpose009"
            geometry={nodes.character_tpose009.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose009.skeleton}
          />
          <skinnedMesh
            name="character_tpose010"
            geometry={nodes.character_tpose010.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose010.skeleton}
          />
          <skinnedMesh
            name="character_tpose011"
            geometry={nodes.character_tpose011.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose011.skeleton}
          />
          <skinnedMesh
            name="character_tpose012"
            geometry={nodes.character_tpose012.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose012.skeleton}
          />
          <skinnedMesh
            name="character_tpose013"
            geometry={nodes.character_tpose013.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose013.skeleton}
          />
          <skinnedMesh
            name="character_tpose014"
            geometry={nodes.character_tpose014.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose014.skeleton}
          />
          <skinnedMesh
            name="character_tpose015"
            geometry={nodes.character_tpose015.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose015.skeleton}
          />
          <skinnedMesh
            name="character_tpose016"
            geometry={nodes.character_tpose016.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose016.skeleton}
          />
          <skinnedMesh
            name="character_tpose017"
            geometry={nodes.character_tpose017.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose017.skeleton}
          />
          <skinnedMesh
            name="character_tpose018"
            geometry={nodes.character_tpose018.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose018.skeleton}
          />
          <skinnedMesh
            name="character_tpose019"
            geometry={nodes.character_tpose019.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose019.skeleton}
          />
          <skinnedMesh
            name="character_tpose020"
            geometry={nodes.character_tpose020.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose020.skeleton}
          />
          <skinnedMesh
            name="character_tpose021"
            geometry={nodes.character_tpose021.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose021.skeleton}
          />
          <skinnedMesh
            name="character_tpose022"
            geometry={nodes.character_tpose022.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose022.skeleton}
          />
          <skinnedMesh
            name="character_tpose023"
            geometry={nodes.character_tpose023.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose023.skeleton}
          />
          <skinnedMesh
            name="character_tpose024"
            geometry={nodes.character_tpose024.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose024.skeleton}
          />
          <skinnedMesh
            name="character_tpose025"
            geometry={nodes.character_tpose025.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose025.skeleton}
          />
          <skinnedMesh
            name="character_tpose026"
            geometry={nodes.character_tpose026.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose026.skeleton}
          />
          <skinnedMesh
            name="character_tpose027"
            geometry={nodes.character_tpose027.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose027.skeleton}
          />
          <skinnedMesh
            name="character_tpose028"
            geometry={nodes.character_tpose028.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose028.skeleton}
          />
          <skinnedMesh
            name="character_tpose029"
            geometry={nodes.character_tpose029.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose029.skeleton}
          />
          <skinnedMesh
            name="character_tpose030"
            geometry={nodes.character_tpose030.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose030.skeleton}
          />
          <skinnedMesh
            name="character_tpose031"
            geometry={nodes.character_tpose031.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose031.skeleton}
          />
          <skinnedMesh
            name="character_tpose032"
            geometry={nodes.character_tpose032.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose032.skeleton}
          />
          <skinnedMesh
            name="character_tpose033"
            geometry={nodes.character_tpose033.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose033.skeleton}
          />
          <skinnedMesh
            name="character_tpose034"
            geometry={nodes.character_tpose034.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose034.skeleton}
          />
          <skinnedMesh
            name="character_tpose035"
            geometry={nodes.character_tpose035.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose035.skeleton}
          />
          <skinnedMesh
            name="character_tpose036"
            geometry={nodes.character_tpose036.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose036.skeleton}
          />
          <skinnedMesh
            name="character_tpose037"
            geometry={nodes.character_tpose037.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose037.skeleton}
          />
          <skinnedMesh
            name="character_tpose038"
            geometry={nodes.character_tpose038.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose038.skeleton}
          />
          <skinnedMesh
            name="character_tpose039"
            geometry={nodes.character_tpose039.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose039.skeleton}
          />
          <skinnedMesh
            name="character_tpose040"
            geometry={nodes.character_tpose040.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose040.skeleton}
          />
          <skinnedMesh
            name="character_tpose041"
            geometry={nodes.character_tpose041.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose041.skeleton}
          />
          <skinnedMesh
            name="character_tpose042"
            geometry={nodes.character_tpose042.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose042.skeleton}
          />
          <skinnedMesh
            name="character_tpose043"
            geometry={nodes.character_tpose043.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose043.skeleton}
          />
          <skinnedMesh
            name="character_tpose044"
            geometry={nodes.character_tpose044.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose044.skeleton}
          />
          <skinnedMesh
            name="character_tpose045"
            geometry={nodes.character_tpose045.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose045.skeleton}
          />
          <skinnedMesh
            name="character_tpose046"
            geometry={nodes.character_tpose046.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose046.skeleton}
          />
          <skinnedMesh
            name="character_tpose047"
            geometry={nodes.character_tpose047.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose047.skeleton}
          />
          <skinnedMesh
            name="character_tpose048"
            geometry={nodes.character_tpose048.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose048.skeleton}
          />
          <skinnedMesh
            name="character_tpose053"
            geometry={nodes.character_tpose053.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose053.skeleton}
          />
          <skinnedMesh
            name="character_tpose054"
            geometry={nodes.character_tpose054.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose054.skeleton}
          />
          <skinnedMesh
            name="character_tpose055"
            geometry={nodes.character_tpose055.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose055.skeleton}
          />
          <skinnedMesh
            name="character_tpose056"
            geometry={nodes.character_tpose056.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose056.skeleton}
          />
          <skinnedMesh
            name="character_tpose057"
            geometry={nodes.character_tpose057.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose057.skeleton}
          />
          <skinnedMesh
            name="character_tpose058"
            geometry={nodes.character_tpose058.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose058.skeleton}
          />
          <skinnedMesh
            name="character_tpose059"
            geometry={nodes.character_tpose059.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose059.skeleton}
          />
          <skinnedMesh
            name="character_tpose060"
            geometry={nodes.character_tpose060.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose060.skeleton}
          />
          <skinnedMesh
            name="character_tpose061"
            geometry={nodes.character_tpose061.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose061.skeleton}
          />
          <skinnedMesh
            name="character_tpose062"
            geometry={nodes.character_tpose062.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose062.skeleton}
          />
          <skinnedMesh
            name="character_tpose063"
            geometry={nodes.character_tpose063.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose063.skeleton}
          />
          <skinnedMesh
            name="character_tpose064"
            geometry={nodes.character_tpose064.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose064.skeleton}
          />
          <skinnedMesh
            name="character_tpose065"
            geometry={nodes.character_tpose065.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose065.skeleton}
          />
          <skinnedMesh
            name="character_tpose066"
            geometry={nodes.character_tpose066.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose066.skeleton}
          />
          <skinnedMesh
            name="character_tpose067"
            geometry={nodes.character_tpose067.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose067.skeleton}
          />
          <skinnedMesh
            name="character_tpose068"
            geometry={nodes.character_tpose068.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose068.skeleton}
          />
          <skinnedMesh
            name="character_tpose074"
            geometry={nodes.character_tpose074.geometry}
            material={materials.spaceman}
            skeleton={nodes.character_tpose074.skeleton}
          />
          <skinnedMesh
            name="helmet003"
            geometry={nodes.helmet003.geometry}
            material={materials.spaceman}
            skeleton={nodes.helmet003.skeleton}
          />
          <skinnedMesh
            name="helmet004"
            geometry={nodes.helmet004.geometry}
            material={materials.spaceman}
            skeleton={nodes.helmet004.skeleton}
          />
        </group>
        <group
          name="Light002"
          position={[-2.08, 1.79, -3.57]}
          rotation={[3.05, -0.4, 2.9]}
        />
        <pointLight
          name="Light"
          intensity={30}
          decay={2}
          color="#5874e1"
          position={[0.67, 1.39, 0.67]}
          rotation={[-1.84, 0.6, 1.93]}
        />
        {/* <pointLight
          name="Light001"
          intensity={1000}
          decay={2}
          color="#ffcee3"
          position={[-0.85, 5.94, 5.74]}
          rotation={[-1.84, 0.6, 1.93]}
        /> */}
      </group>
    </group>
  );
};

useGLTF.preload("/robot.glb");
